apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: nl-amis-testing
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: "1.0"
      environment: testing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: "1.0"
        environment: testing
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim