kind: Service
apiVersion: v1
metadata:
  name: booksservice-v1-0-service
  namespace: nl-amis-testing
  labels:
    app: booksservice
    version: "1.0"
    environment: testing
spec:
  selector:
    app: booksservice
    version: "1.0"
    environment: testing
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30110
    port: 9191
    targetPort: 9091