apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice-v1.0
  namespace: nl-amis-development
  labels:
    app: bookservice
    version: "1.0"
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookservice
      version: "1.0"
      environment: development
  template:
    metadata:
      labels:
        app: bookservice
        version: "1.0"
        environment: development
    spec:
      containers:
      - name: bookservice-v1-0-container
        image: bookservice:v1.0
        env:
        - name: spring.profiles.active
          value: "development"
        ports:
        - containerPort: 9090